### ISSUE TITLE
Fix Storybook

### ISSUE THREAD

**Issue by ErezBiren** [Mathmate-il/mathmate-client#28]
**Describe the bug**
running storybook causes an error

**To Reproduce**
yarn storybook

![image](https://user-images.githubusercontent.com/7828909/218305084-5dd2e11d-cc26-4c0d-83c0-298a6f45df5b.png)

**Comment by tarunsamanta2k20** [comment]
Introduction.stories.mdx does not exists.

**Comment by ErezBiren** [comment]
fixed in #29
